table _data
	lineageTag: 43a389e9-6f4a-4385-96dd-507aab8c9ae9

	column DON1MH-NUMBER
		dataType: string
		lineageTag: 3c808aad-a7f2-42ff-9bff-7a17abde60a8
		summarizeBy: none
		sourceColumn: DON1MH-NUMBER

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DON1MH-ACCEPT
		dataType: string
		lineageTag: 7f445c1b-988b-4934-9138-416a648d887e
		summarizeBy: none
		sourceColumn: DON1MH-ACCEPT

		annotation SummarizationSetBy = Automatic

	column ReactiveResults
		dataType: string
		lineageTag: ff377618-c186-4073-82b1-7a30ce383be9
		summarizeBy: none
		sourceColumn: ReactiveResults

		annotation SummarizationSetBy = Automatic

	column Branch
		dataType: string
		lineageTag: e6272a2c-eafd-4cad-bcef-be4f87ce5c48
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column DON1MH-DATED-ADD
		dataType: dateTime
		formatString: General Date
		lineageTag: d3cb21fe-715a-452a-8434-36e712d73dc8
		summarizeBy: none
		sourceColumn: DON1MH-DATED-ADD

		annotation SummarizationSetBy = Automatic

	column DISCARD-DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: b4c947f1-734f-433d-9658-f3712c8e70d1
		summarizeBy: none
		sourceColumn: DISCARD-DATE

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: d2c2b353-9141-4be0-a468-d57b811184ae
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	column DiscardReason
		dataType: string
		lineageTag: e74a5077-6101-41c6-8270-cdcca2670cfe
		summarizeBy: none
		sourceColumn: DiscardReason

		annotation SummarizationSetBy = Automatic

	partition _data = m
		mode: import
		source =
				let
				    Source = Sql.Database("p-sqldw1601\val", "BMS", [Query="--DECLARE @StartDate DATE = '2025-01-01';#(lf)--DECLARE @EndDate DATE = GETDATE();#(lf)#(lf);WITH Summary AS (#(lf)    SELECT#(lf)        d.[DON1MH-NUMBER],#(lf)        d.[DON1MH-ACCEPT],#(lf)        -- Concatentate comments and handle null values then remove #(lf)        -- the trailing semicolon.#(lf)        TRIM('; ' FROM #(lf)            ISNULL(d.[DON1MH-MHCOM1] + '; ', '') + #(lf)            ISNULL(d.[DON1MH-MHCOM2], '')#(lf)        ) AS comments,#(lf)        -- Concatenate the values remaining from the cross apply and#(lf)        -- seperate by a semicolon.#(lf)        STRING_AGG(#(lf)            CASE WHEN v.result_value = 'R' THEN v.column_name END,#(lf)            '; '#(lf)        ) #(lf)            WITHIN GROUP (ORDER BY v.column_name) AS ReactiveResults,#(lf)        d.[DON1MH-DATED-ADD]#(lf)    FROM bms.dbo.DON1MH AS d #(lf)    CROSS APPLY (#(lf)        -- Unpivot the serology columns#(lf)        VALUES  #(lf)            ('STS', d.[DON1MH-STS]),#(lf)            ('HBSAG', d.[DON1MH-HBSAG]),#(lf)            ('HIV', d.[DON1MH-HIV]),#(lf)            ('HBC', d.[DON1MH-HBC]),#(lf)            ('HCV', d.[DON1MH-HCV]),#(lf)            ('ABORH', d.[DON1MH-ABORH]),#(lf)            ('CMV', d.[DON1MH-CMV]),#(lf)            ('HTLV1', d.[DON1MH-HTLV1])#(lf)    ) AS v(column_name, result_value)#(lf)    GROUP BY #(lf)        d.[DON1MH-NUMBER], #(lf)        d.[DON1MH-ACCEPT], #(lf)        d.[DON1MH-MHCOM1], #(lf)        d.[DON1MH-MHCOM2], #(lf)        d.[DON1MH-DATED-ADD]#(lf)),#(lf)-- Get the discard date as the date the status was updated to N#(lf)DiscardDate AS (#(lf)    SELECT  #(lf)        m.donornum,#(lf)        m.[mh-date],#(lf)        ROW_NUMBER() OVER (PARTITION BY m.donornum ORDER BY m.[mh-date] DESC) AS rn#(lf)    FROM bms.dbo.mhaudit AS m#(lf)    WHERE m.[mh-accept] = 'N'#(lf))#(lf)#(lf)-- Main query #(lf)SELECT  #(lf)    s.[DON1MH-NUMBER], #(lf)    s.[DON1MH-ACCEPT], #(lf)    s.comments,#(lf)    s.ReactiveResults, #(lf)    [p-site].BNAME AS [p-site],#(lf)    --[branch].BNAME AS [branch],#(lf)    s.[DON1MH-DATED-ADD], #(lf)    dd.[mh-date] AS [DISCARD-DATE], #(lf)    r.DiscardReason#(lf)FROM Summary AS s#(lf)#(lf)-- Join on the DON1 table #(lf)LEFT JOIN bms.dbo.DON1 AS d#(lf)    ON s.[DON1MH-NUMBER] = d.[DON1-NUMBER]#(lf)#(lf)-- Get the branch name, and the p site name#(lf)LEFT JOIN bms.dbo.BRANCHES AS [p-site] #(lf)    ON d.[DON1-PROC-SITE] = [p-site].NUMCODE#(lf)#(lf)-- Get the discard date from the DiscardDate cte#(lf)LEFT JOIN DiscardDate AS dd#(lf)    ON s.[DON1MH-NUMBER] = dd.donornum AND dd.rn = 1    #(lf)#(lf)OUTER APPLY (#(lf)    SELECT #(lf)        TRIM(SUBSTRING(#(lf)            a.DiscardReason, #(lf)            PATINDEX('%[a-zA-Z]%', a.DiscardReason), #(lf)            LEN(a.DiscardReason)#(lf)        )) AS DiscardReason#(lf)    FROM (#(lf)        SELECT#(lf)            h.[DON1HT-T1-STAT] AS DiscardReason#(lf)        FROM bms.dbo.DON1HT AS h#(lf)        WHERE s.[DON1MH-NUMBER] = h.[DON1HT-NUMBER]#(lf)            AND dd.[mh-date] IS NOT NULL#(lf)    ) a#(lf)) AS r #(lf)--WHERE dd.[mh-date] >= @StartDate AND dd.[mh-date] <= @EndDate#(lf)"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"p-site", "Branch"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [Branch] <> "Osiris" or [#"DON1MH-DATED-ADD"] <= #datetime(2020, 1, 1, 0, 0, 0)),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Branch] <> "Osiris" or [#"DISCARD-DATE"] <= #datetime(2020, 1, 1, 0, 0, 0) or [#"DISCARD-DATE"] = null),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows1",{{"DON1MH-DATED-ADD", Order.Descending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

